apiVersion: v1
data:
  index.html: |-
    <h1>Joeliton Lima - Prática 3 - Rancher !!!</h1>
kind: ConfigMap
metadata:
  name: landing-page
  labels:
    app: landing-page
    app.kubernetes.io/part-of: landing-page
