apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.0.1.142"],"port":80,"protocol":"HTTP","serviceName":"gitops-app:landing-page","ingressName":"gitops-app:landing-page","hostname":"landing.3.231.24.162.sslip.io","path":"/","allNodes":false}]
  creationTimestamp: '2024-04-15T03:58:17Z'
  generation: 2
  managedFields:
    - apiVersion: networking.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:rules: {}
      manager: rancher
      operation: Update
      time: '2024-04-15T03:58:17Z'
    - apiVersion: networking.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: traefik
      operation: Update
      subresource: status
      time: '2024-04-15T03:58:17Z'
  name: landing-page
  namespace: gitops-app
  resourceVersion: '38476'
  uid: e0454774-55d0-4431-8348-4dc200257ac6
spec:
  rules:
    - host: landing.3.231.24.162.sslip.io
      http:
        paths:
          - backend:
              service:
                name: landing-page
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 10.0.1.142
