apiVersion: networking.k8s.io/v1
kind: route
metadata:
  name: landing-page
  namespace: gitops-app
  labels:
    app.kubernetes.io/part-of: landing-page
spec:
  ingressClassName: traefik
  rules:
    - host: 
      http:
        paths:
          - backend:
              service:
                name: landing-page
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 10.0.1.142
