kind: ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: landing-page
  namespace: gitops-app
spec:
  ingressClassName: traefik
  rules:
    - host: landing.3.231.24.162.sslip.io
      http:
        paths:
          - backend:
              service:
                name: landing-page
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 10.0.1.142
